### ISSUE TITLE
page from branch instead of main

### ISSUE THREAD

**Issue by trutzig89182** [trutzig89182/Mastodon-Sociologists#18]
Right now we run the webpage from main. Would it make sense to rather run it from a branch? Then we could push changes in the csv directly to the webpage branch, and make changes in the overall app in main, before we push it to the webpage branch. What is you thought on this, @nathanlesage?

**Comment by nathanlesage** [comment]
Better (and common) idea: Create a main and a dev branch, we work on the dev branch and only if we're happy we push to main from which the webpage is then served

**Comment by trutzig89182** [comment]
ok, will do this later

**Comment by trutzig89182** [comment]
done
