### ISSUE TITLE
Keywords/Language

### ISSUE THREAD

**Issue by stark1tty** [trutzig89182/Mastodon-Sociologists#29]
Keywords and language are not appearing next to names. See:
https://stark1tty.github.io/Mastodon-Archaeology/
https://github.com/stark1tty/Mastodon-Archaeology/blob/main/resources/users.csv

**Comment by trutzig89182** [comment]
Yes, that is what I am working on at the moment. Made some remarks on what is going on here today: https://www.perspektivbrocken.org/en/2022/11/07/academics-on-mastodon-some-notes-on-a-minimal-web-app-for-creating-customized-following-lists-for-the-fediverse/#more-1833

**Comment by trutzig89182** [comment]
This is discussed in #7 though, so I close this issue.
