### ISSUE TITLE
create better instruction as html file

### ISSUE THREAD

**Issue by trutzig89182** [trutzig89182/Mastodon-Sociologists#3]
- [ ] Upload instruction images seperately to "resources folder"
- [x] Create instructions.html
- [ ] Describe what has to be done
- [ ] Add alt text for better access
- [ ] update reference in index.html

**Comment by trutzig89182** [comment]
Hey @thhaase, vielleicht ist es sinnvoll, wenn du mein Fork noch mal Forkst und wir daran arbeiten?

Unabhängig davon, bin ich etwas verwirrt, weil ich sehe, dass du die Bilddateien hochgeladen hast, ich sie aber nirgendwo finde. Ich würe vorschlagen, sie in resources unter einen unterordner /images zu packen. Hier im thread oben ist auch instructions.html verlinkt, die ich schon mal für die englische Anleitung vorbereitet hatte.

**Comment by trutzig89182** [comment]
@thhaase Nur zur Erkärung: Da ich etwas mehr commits mache, wäre es einfacher, dass wir immer am aktuellsten Stand arbeiten. 
Abgesehen davon, wenn Du irgendwelche Fragen zu GitHub hast, ich bin zwar beileibe kein Experte, aber helfe gerne, wo ich kann.

**Comment by thhaase** [comment]
Ich hatte dir irgendwie rechte gegeben zu meinem repository, kannst du die branches irgendwie wieder zusammenführen? bin etwas verloren, deiner ist aufjedenfall auf dem besten stand... meinen brauchen wir eigentlich nicht

**Comment by thhaase** [comment]
bzgl. der Bilder habe ich erstmal nur rumprobiert... html sieht nicht schwer aus, aber ist neu für mich. Damit du nicht meine ersten htmlversuche aufräumen musst will ich da erstmal selbst etwas rumprobieren und nicht direkt hochladen. 

Schaue schon fleißig tutorials zu github. Ich habs bisher halt echt nur alleine benutzt um dateien zu versionieren und zwischen 2 betriebssystemen zu synchronisieren... forks und branches waren mir ziemlich neu ^^. 
Ich versuche die mergerequests demnächst schneller anzunehmen, jetzt wo ich grob weiß wie das alles geht!

**Comment by thhaase** [comment]
alles ein bisschen kompliziert am anfang

**Comment by trutzig89182** [comment]
Hey Thomas, kannst du vielleicht versuchen auf mein Repository zu gehen, und dann oben auf Fork zu klicken, und dir eine Kopie von meinem Repository zu machen. Sorry, dass das jetzt etwas umständlich ist. Dann wäre es nähmlich nicht so wichtig, dass du die Pull requests bearbeitest. Können gerne auch mal kurz telefonieren, wenn Du magst.

**Comment by trutzig89182** [comment]
Ich habe deinen lezten Commit mal zurückgenommen (die Veränderung der CSV Datei). Da sollten wir vielleicht kurz drüber sprechen. Ich hatte versucht das auf "Most recent first" umzustellen, darum wäre die Alphabetische sortierung gerade nicht so sinnvoll. Der Sinn ist, dass wenn Leute schon eine ältere Version der Liste heruntergeladen haben, sie nicht noch mal alles durchstöbern müssen, sondern oben die neusten einträge finden.

**Comment by thhaase** [comment]
Wir können gerne mal telefonieren. Wann passt es dir denn am besten?

**Comment by trutzig89182** [comment]
Taken up in #27
