### ISSUE TITLE
Improve information given in website

### ISSUE THREAD

**Issue by trutzig89182** [trutzig89182/Mastodon-Sociologists#7]
I try to keep this as minimal as possible concerning user information. But can we make this more informative for users anyway? On direction could be a link at the end of each row, which gets the short bio from the corresponding account and displays it while you hover over it. In this way, we would not extend the csv, but still would be able to give people more relevant information on persons they want to follow.

**Comment by brentonpeterson** [comment]
Another option would be to invite users to contribute a set of maybe 5 keywords that describe their research?  Something like on Google Scholar, where you have limited space.  The goal would be to keep it short, so users can quickly see "Continental political theory" versus "African politics, ethnic politics".

**Comment by trutzig89182** [comment]
Thats a nice Idea. We could also implement it without changing anything. Just adding them after the name could work. Perhaps as hashtags? We could substitute the full link with just a link icon and would have a lot more space.

**Comment by trutzig89182** [comment]
also, #could make filtering possible if we want to put some more work into it. I guess @nathanlesage has a lot of experience with his Zttlr app.

**Comment by trutzig89182** [comment]
Done with including keywords and languages
